ade: 8387
base_lr: 0.05
batch_size: 64
config: ./config/apolloscape/train.yaml
d_model: 32
eval_interval: 1
factor: 1
feeder: feeder.Feeder
history_len: 6
load_checkpt: false
log_interval: 50
num_epoch: 400
num_worker: 10
optimizer: NoamOpt
phase: train
predict_len: 6
print_log: true
start_epoch: 0
step: []
test_batch_size: 1
test_data_cache: ./data/ApolloScape/test_data.pkl
test_data_path: ./data/ApolloScape
test_model: 351
train_data_cache: ./data/ApolloScape/train_data.pkl
train_data_path: ./data/ApolloScape
train_percent: 0.8
val_batch_size: 64
val_test: false
warmup: 5000
weight_decay: 0.0001
work_dir: /home/chen/prediction/apolloscape/s2tnet/s2tnet/checkpoints/apollo
